// Code generated by "stringer -type=PermissionLevel"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownPermission-0]
	_ = x[ReadOnlyPermission-1]
	_ = x[WritePermission-2]
	_ = x[AdminPermission-3]
}

const _PermissionLevel_name = "UnknownPermissionReadOnlyPermissionWritePermissionAdminPermission"

var _PermissionLevel_index = [...]uint8{0, 17, 35, 50, 65}

func (i PermissionLevel) String() string {
	if i < 0 || i >= PermissionLevel(len(_PermissionLevel_index)-1) {
		return "PermissionLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PermissionLevel_name[_PermissionLevel_index[i]:_PermissionLevel_index[i+1]]
}
